#!/bin/env python3
# Created by Tempus Thanos
# Tempus Thanos#2600
# Wolfpack: https://discord.gg/vnVf429TQm
# on 28 Jan 2022 
import pyautogui
import time
pyautogui.FAILSAFE = False

space_key = 'space'
rest_key = '0'

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(1.5)
pyautogui.keyDown(space_key)
pyautogui.keyUp(space_key)
time.sleep(0.5)

pyautogui.keyDown(rest_key)
pyautogui.keyUp(rest_key)
time.sleep(60)